name: CorpusChristi
favicon: null
layout_spectrum: 0.24885980901308358
typography_spectrum: 0.07315168995410204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9744211882352829
  lightness: 0.650635882280767
  saturation: 0.2129029887728393
  rhythmicContrast: 0.5969847848173231
purpose: []
